#! /bin/sh

sxhkd -C ~/.config/bspwm/sxhkdrc &
picom -b --experimental-backends

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

nitrogen --restore &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap       	 0
bspc config top_padding          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
