#!/bin/bash


sudo apt-get install -y pv
sudo apt-get install -y iw
sudo apt-get install -y xcb
sudo apt-get install -y sox
sudo apt-get install -y vlc
sudo apt-get install -y mdp
sudo apt-get install -y ncal
sudo apt-get install -y kmix
sudo apt-get install -y lynx
sudo apt-get install -y tree
sudo apt-get install -y inxi
sudo apt-get install -y cmus
sudo apt-get install -y xsdt
sudo apt-get install -y ccal
sudo apt-get install -y mtpfs
sudo apt-get install -y micro
sudo apt-get install -y atool
sudo apt-get install -y socat
sudo apt-get install -y aewan
sudo apt-get install -y cmark
sudo apt-get install -y gnupg
sudo apt-get install -y nsnake
sudo apt-get install -y bastet
sudo apt-get install -y figlet
sudo apt-get install -y catimg
sudo apt-get install -y elinks
sudo apt-get install -y pandoc
sudo apt-get install -y gputils
sudo apt-get install -y odt2txt
sudo apt-get install -y calibre
sudo apt-get install -y pcmanfm
sudo apt-get install -y redshift
sudo apt-get install -y whiptail
sudo apt-get install -y powertop
sudo apt-get install -y cpufetch
sudo apt-get install -y markdown
sudo apt-get install -y fontforge
sudo apt-get install -y ninvaders
sudo apt-get install -y mediainfo
sudo apt-get install -y colordiff
sudo apt-get install -y xautolock
sudo apt-get install -y setxkbnap
sudo apt-get install -y linuxlogo
sudo apt-get install -y mesa-utils
sudo apt-get install -y renameutils
sudo apt-get install -y mupdf-tools
sudo apt-get install -y bucklespring
sudo apt-get install -y usb-creator-gtk
sudo apt-get install -y gnome-bluetooth
sudo apt-get install -y volumeicon-alsa
sudo apt-get install -y cool-retro-term
sudo apt-get install -y gnome-screenshot
sudo apt-get install -y ffmpegthumbnailer
