#!/bin/bash

nvims() {
	items=("default"  "lazyNvim" "nvChad" "astroNvim" "kickStart")
	config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --layout=reverse --border --exit-0)
	if [[ -z $config ]]; then
		echo "Nothing selected"
		return 0
	elif [[ $config == "default" ]]; then
		config=""
	fi
	NVIM_APPNAME=$config nvim "$@"
}

nvims "$@"
