#!/bin/bash

nvims() {
	items=("lvim" "default")

	config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --layout=reverse --pointer="⚡" --border=rounded --margin 2% --height 60% --exit-0)
	if [[ -z $config ]]; then
		echo "Nothing selected"
		return 0
	elif [[ $config == "default" ]]; then
		config=""
		NVIM_APPNAME=$config nvim "$@"
	elif [[ $config == "lvim" ]]; then
		NVIM_APPNAME=$config nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
	else
		NVIM_APPNAME=$config nvim "$@"
	fi

}

nvims "$@"
