#!/bin/bash


mkdir -p ~/.tmux/servers
touch ~/.tmux/servers/serverlist.txt
random_word=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
echo "$random_word" >> ~/.tmux/servers/serverlist.txt
tmux -L ${random_word}
