#!/bin/bash


mkdir -p ~/.tmux/oldresurrect

echo ""
read -p "NEW / UPDATE / RENAME ? [n/u/r] :  " option

if [[ $option == "n" || $option == "N" ]]; then

    defaultname=$(readlink -f ~/.tmux/resurrect/last)

    dir_path=$(dirname ${defaultname})

    read -p "Enter new name to save : " newname

    newlocation="${dir_path}/${newname}.txt"

    if [[ $newname != "" ]]; then

        mv ${defaultname} ${newlocation}

        ln -sf ${newlocation} ~/.tmux/resurrect/last
    fi

elif [[  $option == "u" || $option == "U" ]]; then

    toupdate=$(find ~/.tmux/resurrect -type f | fzf)

    oldname=$(readlink -f ~/.tmux/resurrect/last)

    if [[ ${toupdate} != ${oldname} ]]; then

        if [[ $toupdate != "" ]]; then

            mv ${toupdate} ~/.tmux/oldresurrect

            mv ${oldname} ${toupdate}

            ln -sf ${toupdate} ~/.tmux/resurrect/last
        fi
    fi

elif [[  $option == "r" || $option == "R" ]]; then

    torename=$(find ~/.tmux/resurrect -type f | fzf)

    dir_path=$(dirname ${torename})

    read -p "Rename : " newname

    newlocation="${dir_path}/${newname}.txt"

    if [[ $torename != "" ]]; then

        mv ${torename} ${newlocation}

        ln -sf ${newlocation} ~/.tmux/resurrect/last
    fi

fi
